image: Visual Studio 2017

version: Oops{build}

#
# 在 Appveyor 控制台设置的
#
# Branches to build
#   All except branches specified below
#     master
#
# [x] Do not build tags
#

platform: Any CPU

configuration:
  - Debug
  #- Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(p_version)
  assembly_file_version: $(p_version)
  assembly_informational_version: $(p_version)
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(p_version)
  package_version: $(p_version)
  assembly_version: $(p_version)
  file_version: $(p_version)
  informational_version: $(p_version)

install:
  - ps: ./CI/appveyor_init.ps1

before_build:
  - nuget restore -Verbosity quiet
  - msbuild /t:Clean /verbosity:quiet /nologo

artifacts:
  - path: BililiveRecorder.WPF\bin\Debug
    name: BililiveRecorderDebugBuild

environment:
  github_access_token:
    secure: 3n2WMbrqWb0nmy2LBmu7w6dJltiHHC4LCoNuIKBh7fKV0xfxCwVGOxbTpunLI2pe

cache:
  - packages

build:
  verbosity: minimal

after_build:
  - ps: ./CI/appveyor_after_build.ps1

before_deploy:
  - ps: ./CI/appveyor_before_deploy.ps1


# after_deploy:

# clone soft.danmuji.org
# copy files
#  - git commit ...
#  - git push ...

# TODO: Github Release

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
