image: Visual Studio 2017
platform: Any CPU
# skip_non_tags: true

version: 0.0.0.{build}

init:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "appveyor@genteure.com"
  - git config --global user.name "Appveyor(Genteure)"
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
        $env:p_version="$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
        Update-AppveyorBuild -Version "$env:p_version"
      }
      else
      {
        $env:p_version="0.0.0.$env:APPVEYOR_BUILD_NUMBER"
        Update-AppveyorBuild -Version "dev-$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))"
      }
  - ps: Write-Host $env:p_version

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '${p_version}'
  assembly_file_version: '${p_version}'
  assembly_informational_version: '${p_version}'
dotnet_csproj:
  patch: true
  file:
    - 'BililiveRecorder.Core\BililiveRecorder.Core.csproj'
    - 'BililiveRecorder.FlvProcessor\BililiveRecorder.FlvProcessor.csproj'
  version: '${p_version}'
  package_version: '${p_version}'
  assembly_version: '${p_version}'
  file_version: '${p_version}'
  informational_version: '${p_version}'

before_build:
  - nuget restore
  - dotnet restore

artifacts:
  - path: BililiveRecorder.WPF\bin\Debug
    name: WPFDebug

environment:
  github_access_token:
    secure: 3n2WMbrqWb0nmy2LBmu7w6dJltiHHC4LCoNuIKBh7fKV0xfxCwVGOxbTpunLI2pe
build:
  verbosity: minimal
on_success:
# clone soft.danmuji.org
# copy files
#  - git commit ...
#  - git push ...

# TODO: Github Release

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
