version: 1.0.{build}
skip_non_tags: true
image: Visual Studio 2017
configuration:
- Debug
- Release
platform: Any CPU
init:
  - git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "appveyor@genteure.com"
  - git config --global user.name "Appveyor(Genteure)"
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
environment:
  github_access_token:
    secure: 3n2WMbrqWb0nmy2LBmu7w6dJltiHHC4LCoNuIKBh7fKV0xfxCwVGOxbTpunLI2pe
build:
  verbosity: minimal
on_success:
# clone soft.danmuji.org
# copy files
#  - git commit ...
#  - git push ...

# TODO: Github Release
