image: Visual Studio 2017

version: Oops{build}

platform: Any CPU

branches:
  except:
  - master
skip_tags: true

configuration:
  - Debug
  #- Release

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: $(p_version)
  assembly_file_version: $(p_version)
  assembly_informational_version: $(p_version)
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(p_version)
  package_version: $(p_version)
  assembly_version: $(p_version)
  file_version: $(p_version)
  informational_version: $(p_version)

artifacts:
  - path: BililiveRecorder.WPF\bin\Debug
    name: BililiveRecorderDebugBuild

environment:
  github_access_token:
    secure: 3n2WMbrqWb0nmy2LBmu7w6dJltiHHC4LCoNuIKBh7fKV0xfxCwVGOxbTpunLI2pe
  codesignaes:
    secure: 9f78dD9jN5vlVZ0zv15kdD4Mj+/+uacfu29bbGC+cBVFs834aFVf5Ci+n3NP3Bl7
  codesignpasswd:
    secure: iKv14aGuHUDEfb5fSIBMuSsu1JnisWXL8wJ7x/2DCNtggWKevjhOFBOrI7c95xBY

cache:
  - packages

install:
  - ps: ./CI/appveyor_install.ps1

before_build:
  - nuget restore -Verbosity quiet
  - msbuild /t:Clean /verbosity:quiet /nologo

build:
  verbosity: minimal

after_build:
  - ps: ./CI/appveyor_after_build.ps1

on_success:
  - ps: ./CI/appveyor_on_success.ps1


# after_deploy:

# clone soft.danmuji.org
# copy files
#  - git commit ...
#  - git push ...

# TODO: Github Release

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
